<?php

/**
 * @file
 * Primary module hooks for Social Hub module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function social_hub_theme() {
  $base_variables = [
    'url' => NULL,
    'link_type' => NULL,
    'icon' => NULL,
    'text' => NULL,
    'attributes' => NULL,
    'extras' => NULL,
  ];

  $share_variables = [
    'sharing_mode' => NULL,
    'script' => NULL,
  ];

  $hooks = [
    'share' => [
      'variables' => $share_variables + $base_variables,
      'template' => 'share',
    ],
    'share__embed' => [
      'template' => 'share--embed',
    ],
    'follow' => [
      'variables' => $base_variables,
      'template' => 'follow',
    ],
  ];

  return $hooks;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function social_hub_theme_suggestions_share(array $variables) {
  $suggestions[] = 'share__' . $variables['sharing_mode'];

  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_hub_preprocess_share(&$variables) {
  _social_hub_preprocess_plugin($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_hub_preprocess_share__embed(&$variables) {
  _social_hub_preprocess_plugin($variables);
  $variables['embed_attributes'] = new Attribute($variables['extras']['embed_attributes']);
  $variables['embed_value'] = $variables['extras']['embed_value'];
  unset($variables['extras']);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_hub_preprocess_follow(&$variables) {
  _social_hub_preprocess_plugin($variables);
}

/**
 * Preprocess theme variables for plugins.
 *
 * @param array $variables
 *   An array of variables to preprocess.
 *
 * @internal
 */
function _social_hub_preprocess_plugin(array &$variables) {
  $variables['attributes'] = new Attribute($variables['attributes']);
  $variables['attributes']->setAttribute('href', $variables['url']);
  // @TODO Make icons set configurable.
  $variables['icon'] = 'fab ' . $variables['icon'];
}

/**
 * Implements hook_library_info_build().
 */
function social_hub_library_info_build() {
  /** @var \Drupal\Core\Config\Entity\ConfigEntityStorageInterface $storage */
  $storage = \Drupal::service('entity_type.manager')->getStorage('platform');
  $results = $storage->getQuery()
    // @TODO Refactor to use an interface instead of fixed config value.
    ->condition('plugins.*', ['share'], 'IN')
    ->execute();
  $entities = [];
  $libraries = [];

  if (!empty($results)) {
    /** @var \Drupal\social_hub\PlatformInterface[] $entities */
    $entities = $storage->loadMultiple($results);
  }

  if (empty($entities)) {
    return [];
  }

  foreach ($entities as $entity) {
    /** @var \Drupal\social_hub\PlatformIntegrationPluginInterface $plugin */
    $plugin = $entity->getPluginCollection()->get('share');
    $configuration = $plugin->getConfiguration();
    if (empty($configuration['script_type']) || $configuration['script_type'] !== 'external') {
      continue;
    }

    $namespace = "{$entity->id()}_share";
    $libraries += [
      $namespace => [
        'js' => [],
      ],
    ];
    $libraries[$namespace]['js'][$configuration['external']['url']] = [
      'type' => 'external',
      'attributes' => $configuration['external']['attributes'],
      'preprocess' => $configuration['external']['preprocess'],
    ];

    $browsers = array_filter(_social_hub_process_browsers_rule($configuration['external']['browsers']));

    if (!empty($browsers)) {
      $libraries[$namespace]['js'][$configuration['external']['url']]['browsers'] = $browsers;
    }
  }

  return $libraries;
}

/**
 * Process supported browsers rule.
 *
 * Rules are stored using key/values text separated by colons and commas.
 * E.g.: 'IE:lte IE 9,!IE:false'.
 *
 * @param string $string
 *   The rule.
 *
 * @return array
 *   The supported browsers array.
 *
 * @internal
 */
function _social_hub_process_browsers_rule($string) {
  $tmp = explode(',', $string);

  if (empty($tmp)) {
    return [];
  }

  if (!is_array($tmp)) {
    return [];
  }

  $rules = [];

  foreach ($tmp as $item) {
    $rules += explode(':', $item);
  }

  return $rules;
}
