social_hub.platform.*:
  type: config_entity
  label: Platform
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    plugins:
      type: sequence
      label: Plugins
      sequence:
        type: string
        label: Plugin
    configuration:
      type: sequence
      label: Configuration
      sequence:
        type: social_hub.platform.plugin.[%key]

social_hub_platform_configuration:
  type: config_object
  label: Configuration
  mapping:
    id:
      type: string
      label: Plugin ID
    link:
      type: mapping
      label: 'Link settings'
      mapping:
        type:
          type: string
          label: 'Link type'
        icon:
          type: string
          label: 'Link icon'
        text:
          type: label
          label: 'Link text'
        title:
          type: label
          label: 'Link title'
        classes:
          type: string
          label: 'Link CSS classes'

social_hub.platform.plugin.*:
  type: social_hub_platform_configuration

social_hub.platform.plugin.follow:
  type: social_hub_platform_configuration
  mapping:
    platform_url:
      type: string
      label: 'Platform URL'
    follow_path:
      type: string
      label: 'Follow path'

social_hub.platform.plugin.share:
  type: social_hub_platform_configuration
  mapping:
    sharing_mode:
      type: string
      label: 'Sharing mode'
    url:
      type: string
      label: URL
    embed:
      type: string
      label: Embed
    script_type:
      type: string
      label: 'Script type'
    inline:
      type: string
      label: 'Inline script'
    library:
      type: string
      label: 'library'
    external:
      type: mapping
      label: 'External script'
      mapping:
        url:
          type: string
          label: URL
        attributes:
          type: mapping
          label: Attributes
          mapping:
            async:
              type: boolean
              label: 'Load asynchronously'
            minified:
              type: boolean
              label: Minified
        preprocess:
          type: boolean
          label: Preprocess
        browsers:
          type: string
          label: Browsers
